on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make
      - name: 'Get PDF'
        uses: actions/upload-artifact@v3
        with:
          name: thesis
          path: thesis.pdf
      - name: 'Get word count'
        uses: actions/upload-artifact@v3
        with:
          name: thesis
          path: wordcount.txt
