on: [push]
jobs:
  create-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set timestamp environment variable
        run: echo "timestamp=$(date +'%Y-%m-%d-%H%M%S')" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make
      - name: 'Get PDF'
        uses: actions/upload-artifact@v3
        with:
          name: thesis-${{ env.timestamp }}
          path: thesis.pdf
      - name: 'Get word count'
        uses: actions/upload-artifact@v3
        with:
          name: thesis-${{ env.timestamp }}
          path: wordcount.txt
